// <auto-generated />
namespace Notificaciones.Module.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ModificandoCampoFechaProgramada : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ModificandoCampoFechaProgramada));
        
        string IMigrationMetadata.Id
        {
            get { return "202309140305452_Modificando-Campo-FechaProgramada"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
