// <auto-generated />
namespace Notificaciones.Module.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AgregandoCampoLeido : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AgregandoCampoLeido));
        
        string IMigrationMetadata.Id
        {
            get { return "202309142337329_Agregando-Campo-Leido"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
