// <auto-generated />
namespace Notificaciones.Module.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class CreandoEntidadesNotificacion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreandoEntidadesNotificacion));
        
        string IMigrationMetadata.Id
        {
            get { return "202309040005484_Creando-Entidades-Notificacion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
